### ISSUE TITLE
Deleting a record in the admin cause pagination to reset

### ISSUE THREAD

**Issue by tomgco** [serby/ctrl#107]
When deleting a record in the cms, if the user is on page 3 and deletes a record the pagination resets back to the first record.

**Comment by tomgco** [comment]
@aduncan88 mentioned to me that he has fixed this before, however is not aware if it has been merged upstream.

**Comment by serby** [comment]
@aduncan88 Can you send a pull request for ctrl?

**Comment by microadam** [comment]
Yep. It was a one line change as far as I remember. Just need to find which control project I fixed it in.

**Comment by serby** [comment]
@aduncan88 can you put this in 0.1 please

**Comment by serby** [comment]
@microadam is this done?

**Comment by microadam** [comment]
Have now, see latest pull request

**Comment by microadam** [comment]
This can be closed now
