### ISSUE TITLE
Admin first run user journey: hangs, crashes

### ISSUE THREAD

**Issue by bengourley** [serby/ctrl#116]
Fresh checkout of 0.1 branch:
- `git checkout 0.1`
- `rm -rf node_modules`
- `npm install`

Delete db:
- `mongo`
- `> use ctrl-development`
- `>`db.dropDatabase()`

http://localhost:3021/admin

Fill in details, hit enter... hangs, then crashed with no error message

**Comment by serby** [comment]
Here is the one-liner to drop db

```
 echo 'db.dropDatabase()' | mongo ctrl-development
```

**Comment by bengourley** [comment]
Issue was to do with bcrypt. `npm rebuild` fixed the issue on node 0.8.9.
