### ISSUE TITLE
make lint not passing

### ISSUE THREAD

**Issue by serby** [serby/ctrl#124]
Creating a better lint target, has shown up lots of areas where there are lint problems. These need fixing. 

run the following from the project root to see the errors to fix

```
 make lint
```

**Comment by domharrington** [comment]
Just been speaking to @bengourley about this. The only error that comes up for me is:

```
./lib/http-error-handler.js: line 12, col 38, 'next' is defined but never used.

1 error
make: *** [lint] Error 1
```

The line in question:

```
return function(err, req, res, next) {
```

This is required for Express error-handling middleware http://expressjs.com/guide.html#error-handling even though we don't use the `next` parameter. Any suggestions for how we can get around this problem?

**Comment by domharrington** [comment]
This problem can be avoided by adding the following line to the top of http-error-handler.js:

```
/*jshint unused:false */
```

Seems a bit hacky and could potentially mean we miss other linting problems from this file.

**Comment by serby** [comment]
We had this debate in the last tech meeting. I think that is the best option we have.

**Comment by tomgco** [comment]
I thought we decided in our tech meeting @serby that we were going to assign the parameter to itself as this suppresses all unused errors in that file? 

```
req = req
```
