### ISSUE TITLE
404 page styles

### ISSUE THREAD

**Issue by domharrington** [serby/ctrl#144]
The styles appear to be broken on the 404/error page. Is there any reason why they do not extend the layout that is present throughout the rest of the front end?

**Comment by jackbrewer** [comment]
I've fixed the visual bugs, but by duplicating the template with 2 minor changes.

The main problem I encountered is that while the error page can technically extend the default template, it doesn't have a 'page' variable defined to set page title and body class. This is causing errors.

If someone more technical can assist with that, I can remove the duplicate template.
