### ISSUE TITLE
Upgrading to Stylus 0.23.0 breaks versionPath helper

### ISSUE THREAD

**Issue by domharrington** [serby/ctrl#25]
With stylus 0.22.0 using the versionPath helper produces the following css:

`background-image: url("/images/admin/content/0.0.1/logo-control.png")`

After the upgrade to stylus 0.23.0 the following css is produced:

`background-image: 'url("/images/admin/content/0.0.1/logo-control.png")'`

This breaks the functionality of the helper and produces unexpected results.

**Comment by serby** [comment]
Bugger! I'll take a look.

**Comment by bengourley** [comment]
This is fixed.
