### ISSUE TITLE
Generic Delete is a GET and is a minor security concern

### ISSUE THREAD

**Issue by serby** [serby/ctrl#47]

**Comment by bengourley** [comment]
What is the reason it's not a DELETE?

**Comment by serby** [comment]
Because it is a link. We'd need to make it Ajax and implement a service to make it a DELETE. Defiantly doable

**Comment by bengourley** [comment]
Or the place with the link could be a form with method override? (Bit hacky, but simplifies the client)

**Comment by evlun** [comment]
@bengourley I don't think that's an option. If I recall correctly, only GET and POST methods are possible through HTML forms.

**Comment by bengourley** [comment]
http://www.senchalabs.org/connect/middleware-methodOverride.html

**Comment by evlun** [comment]
Cool!

**Comment by serby** [comment]
The security risk that Noake was pointing out is one of CSRF
http://en.wikipedia.org/wiki/Cross-site_request_forgery

Currently if you can get your user ID I can create an image element like
this:

<img src="
http://localhost:3021/admin/administrator/507a910677ce00ed21000002/delete">

Put that on a remote page, get an authed ctrl admin to view the page, and
boom! No more administrator!

This would be fixed to some extent with a POST request so the DELETE method
is not important.

On 16 October 2012 09:52, Erik Lundin notifications@github.com wrote:

> Cool!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/serby/ctrl/issues/47#issuecomment-9477297.

## 

paul.serby@clock.co.uk
Chief Technology Officer

_Direct: +44 2030 516115__Mobile: +44 7881 550999_
*

## *
- http://www.clock.co.uk/
  *
  *
  *
  The Old School HouseBridge Road, Hunton Bridge,Kings Langley, WD4 8RQ
  Switchboard: +44 1923 261166www.clock.co.uk
  *
  *
- http://twitter.com/clock    https://github.com/clocklimited
  http://www.linkedin.com/company/clock-limited
  http://www.clock.co.uk/blog
  *
  *
  *
  _www.clock.co.uk/email-disclaimer_
  _clock.® is a Registered Trademark of Clock Limited in the European
  Community and other territories_

**Comment by domharrington** [comment]
Does this look okay? Just spoken to Jack who is gunna take a look at styling when he gets a chance.

**Comment by bengourley** [comment]
2 things:
- Can you update the selector here: https://github.com/serby/ctrl/blob/master/bundles/admin/public/js/admin.js#L186 so that you get a confirm dialog when you hit that delete button.
- I still get delete link on hover:

![error](http://f.cl.ly/items/1e180A1m0T463J2B1y0H/Screen%20Shot%202012-11-13%20at%2012.23.06.png)

**Comment by domharrington** [comment]
Removed the delete link from the list, I accidentally left it there for debugging. I didn't put the issue number in the commit, will it still get merged?
