### ISSUE TITLE
Article Bundle: Route is greedy

### ISSUE THREAD

**Issue by bengourley** [serby/ctrl#57]
The route in the article bundle is really vague:

```
app.get('/:section/:article', ...)
```

This means that any bundles added after it can't have routes in the form `/foo/bar`.

e.g:

```
bundled.addBundles(__dirname + '/bundles/', [
  ...
  'article',
  'pageAdmin',
]);
```

My 'pageAdmin' bundle wants `/admin/page`, but this won't be reached because the article bundle preceded it (and takes precedence).

It's easy to resolve–just change the order, but could this be a problem further down the line? Is there a better solution?

**Comment by serby** [comment]
I've been managing it by putting it as the last bundle to load. I'm not sure there is any other solution other than prefixing the URL path, which I don't really want to do.

**Comment by bengourley** [comment]
Yep, no good to have to change the url. I guess this is one of the issues of using Express, though I don't know how other frameworks handle routing precedence.

**Comment by bengourley** [comment]
This is now fixed. Article bundles calls `next()` rather than 404ing itself.
