### ISSUE TITLE
Can't put stylus files in bundles' public route

### ISSUE THREAD

**Issue by bengourley** [serby/ctrl#64]
The Stylus middleware can't deal with multiple paths, nor when the requested url doesn't match the file's path.

We could farm out most of the stuff from `stylus.middleware` and make our own middleware.

Thoughts?

**Comment by bengourley** [comment]
As it stands we can put all public resources within a bundle, but not CSS. That has to live in `/public/`.

**Comment by serby** [comment]
It is the current intention that the CSS ie theming of an application is not contained in a bundle. This is probably why we've not noticed this before. If we wanted to have /themes/{default,fancy,modern} with all the CSS and theme imagery in that should still work right?

**Comment by bengourley** [comment]
This is less to do with theming and more to do with structuring the css. A control instance that has 3/50 available modules on will have 47 extra styles going on in the `/public/css` directory. I think it just makes sense to modularise the CSS like we can with the JS and images etc.

**Comment by serby** [comment]
I'm not sure. We've been around this a few times with Jack and I thought
that we had decided not to go with that approach. Let's have a 3 way call
with Jack once he is back to confirm a way forward.

Regardless of the outcome, your issue still needs addressing.

On 22 May 2012 16:38, Ben Gourley <
reply@reply.github.com

> wrote:
> 
> This is less to do with theming and more to do with structuring the css. A
> control instance that has 3/50 available modules on will have 47 extra
> styles going on in the `/public/css` directory. I think it just makes sense
> to modularise the CSS like we can with the JS and images etc.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/serby/control/issues/64#issuecomment-5850337

## 

paul.serby@clock.co.uk
Chief Technology Officer

_Direct: +44 2030 516115__Mobile: +44 7881 550999_
*

## *
- http://www.clock.co.uk/
  *
  *
  *
  The Old School HouseBridge Road, Hunton Bridge,Kings Langley, WD4 8RQ
  Switchboard: +44 1923 261166www.clock.co.uk
  *
  *
- http://twitter.com/clock    https://github.com/clocklimited
  http://www.linkedin.com/company/clock-limited
  http://www.clock.co.uk/blog
  *
  *
  *
  _www.clock.co.uk/email-disclaimer_
  _clock.® is a Registered Trademark of Clock Limited in the European
  Community and other territories_

**Comment by bengourley** [comment]
Ok. I've knocked up a piece of middleware that does the job but I'll show you tomorrow.

**Comment by serby** [comment]
This is fixed in the 0.1 branch
