### ISSUE TITLE
More form styles are needed to set the size of textareas

### ISSUE THREAD

**Issue by serby** [serby/ctrl#70]
Sometimes you need to say that a textarea is: shortest, short, tall, tallest or smallest, small, big, bigest. I have been added these styles on projects that need them, but it would be good to have a more considered set of modifiers in control.

**Comment by serby** [comment]
Also we need to be able to have a textarea that takes the full width of a form. It would be good if this was the default when a textarea is not in a .form-row. 

/cc @bengourley

**Comment by serby** [comment]
Article body is an example of a place we need this: http://localhost:3021/admin/article/new

**Comment by jackbrewer** [comment]
I'm currently rewriting some standard form element markup and styling in a private repo (@serby you have access) which will be open-sourced after a bit more work.

I'll be sure to take this into account, then the ctrl forms will likely be refactored to use the new structure. Is this issue something which can wait a while, or would you like a temporary fix for now?

**Comment by bengourley** [comment]
How do you get a not full width one currently?

**Comment by serby** [comment]
It can wait for now, I know you are busy.

I've put in place a temporary fix in my last commit 2dc3bfb8fa928da1d70d4abf1177bda70b2a8abe

**Comment by serby** [comment]
@bengourley See the article create page now for an example of what I was after.

**Comment by bengourley** [comment]
Sure, but there is currently no 'textarea' property type in the view schema. There should be. The custom article admin form is very WET.

**Comment by serby** [comment]
There is a textbox in the generic form on line 51 of form.jade

I don't have a massive problem with some duplication in view templates. The
alternative is to add complexity to the generic logic to handle more
concevable UI possibility which would be worst than a bit of copy and paste
in the view layer.

On 14 October 2012 21:07, Ben Gourley notifications@github.com wrote:

> Sure, but there is currently no 'textarea' property type in the view
> schema. There should be. The custom article admin form is very WET.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/serby/ctrl/issues/70#issuecomment-9425343.

## 

paul.serby@clock.co.uk
Chief Technology Officer

_Direct: +44 2030 516115__Mobile: +44 7881 550999_
*

## *
- http://www.clock.co.uk/
  *
  *
  *
  The Old School HouseBridge Road, Hunton Bridge,Kings Langley, WD4 8RQ
  Switchboard: +44 1923 261166www.clock.co.uk
  *
  *
- http://twitter.com/clock    https://github.com/clocklimited
  http://www.linkedin.com/company/clock-limited
  http://www.clock.co.uk/blog
  *
  *
  *
  _www.clock.co.uk/email-disclaimer_
  _clock.® is a Registered Trademark of Clock Limited in the European
  Community and other territories_

**Comment by bengourley** [comment]
Ah I couldn't find that before. Thanks.

I think we should have the most common form controls in generic, though. It can be really powerful to have them, and as we've experienced, developers like to use them as they are a quick win.

**Comment by serby** [comment]
Agreed. Maybe there needs to be a class that makes them full width.

On 15 October 2012 12:17, Ben Gourley notifications@github.com wrote:

> Ah I couldn't find that before. Thanks.
> 
> I think we should have the most common form controls in generic, though.
> It can be really powerful to have them, and as we've experienced,
> developers like to use them as they are a quick win.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/serby/ctrl/issues/70#issuecomment-9441625.

## 

paul.serby@clock.co.uk
Chief Technology Officer

_Direct: +44 2030 516115__Mobile: +44 7881 550999_
*

## *
- http://www.clock.co.uk/
  *
  *
  *
  The Old School HouseBridge Road, Hunton Bridge,Kings Langley, WD4 8RQ
  Switchboard: +44 1923 261166www.clock.co.uk
  *
  *
- http://twitter.com/clock    https://github.com/clocklimited
  http://www.linkedin.com/company/clock-limited
  http://www.clock.co.uk/blog
  *
  *
  *
  _www.clock.co.uk/email-disclaimer_
  _clock.® is a Registered Trademark of Clock Limited in the European
  Community and other territories_

**Comment by serby** [comment]
@jackbrewer Does #131 address this?

**Comment by jackbrewer** [comment]
Yes, if you are happy with passing the textarea mixin a 'rows' attribute rather than passing a class - I've implemented this.

It's more flexible as you can have bespoke heights per textarea and don't need to remember a group of class names

**Comment by jackbrewer** [comment]
And there is now a class of .form-row-full-width to make form elements drop below their labels and span the full width of the form.

Currently this has only been tested with textareas, which is really the only place it's needed for now. A full suite of full-width form elements is in the works but enough work has been done to close this issue.

**Comment by serby** [comment]
What about classes for height?

**Comment by jackbrewer** [comment]
That's what the optional 'rows' attribute is doing that I mentioned before.

For a height of 25 lines of text:
mixin textboxFieldForObject( { ... }, { ... label: 'Article Content', rows: 25 ... })

This also means the textarea height is always a multiple of the line-height, so text on the last line shouldn't get cut off.

We can do classes if you like, but this gives more flexibility and means less CSS.

**Comment by serby** [comment]
Sorry I missed your first comment about rows. Sounds good, I'll have to give it go.
