### ISSUE TITLE
Better password hashing

### ISSUE THREAD

**Issue by serby** [serby/ctrl#76]
Password checking in the authentication module should use this method.

http://throwingfire.com/storing-passwords-securely/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+throwingfire+%28Throwing+Fire%29#notpasswordhashes

**Comment by serby** [comment]
Luke Wilde started to refactor the access control out to its own bundle. It would be worth speaking to him and seeing how far he got. Possible someone could take over from him.

**Comment by evlun** [comment]
This was implemented through https://github.com/serby/control/pull/99.
