### ISSUE TITLE
Convert code base to comma first

### ISSUE THREAD

**Issue by serby** [serby/ctrl#77]
As per: https://gist.github.com/357981

**Comment by serby** [comment]
@oliverjohnstone Has this been completed now? If not can you reference #77 in all your future commits and let me know when it is complete.

**Comment by oliverjohnstone** [comment]
Yes I believe so, all the files that I believe are part of the project should now be converted.

----- Reply message -----
From: "Paul Serby" reply@reply.github.com
To: "Oliver Johnstone" oliver@ojs.co
Subject: [control] Convert code base to comma first (#77)
Date: Mon, Jun 25, 2012 5:08 pm

@oliverjohnstone Has this been completed now? If not can you reference #77 in all your future commits and let me know when it is complete.

---
