### ISSUE TITLE
Tabs need to be converted to spaces.

### ISSUE THREAD

**Issue by domharrington** [serby/ctrl#78]
Quite a few files still have tabs instead of spaces. Would be good to fix this for consistency.

**Comment by serby** [comment]
I agree. I little script could be run to convert everything.

**Comment by serby** [comment]
Fixed in c4398d718d2a5bd7854c29693d07ae38c32fafe5

**Comment by domharrington** [comment]
This seems to have converted some files to 8 spaces e.g. https://github.com/serby/control/blob/master/bundles/admin/views/adminBar.jade

**Comment by serby** [comment]
Yeah I just spotted this. It's a bugger to fix now. I'm going to have to revert to the tab version and reconvert

**Comment by serby** [comment]
I had to do a --force to sort this. I'm not proud of myself. Everyone needs
to repull.

On 7 June 2012 12:37, domharrington <
reply@reply.github.com

> wrote:
> 
> This seems to have converted some files to 8 spaces e.g.
> https://github.com/serby/control/blob/master/bundles/admin/views/adminBar.jade
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/serby/control/issues/78#issuecomment-6173863

## 

paul.serby@clock.co.uk
Chief Technology Officer

_Direct: +44 2030 516115__Mobile: +44 7881 550999_
*

## *
- http://www.clock.co.uk/
  *
  *
  *
  The Old School HouseBridge Road, Hunton Bridge,Kings Langley, WD4 8RQ
  Switchboard: +44 1923 261166www.clock.co.uk
  *
  *
- http://twitter.com/clock    https://github.com/clocklimited
  http://www.linkedin.com/company/clock-limited
  http://www.clock.co.uk/blog
  *
  *
  *
  _www.clock.co.uk/email-disclaimer_
  _clock.® is a Registered Trademark of Clock Limited in the European
  Community and other territories_

**Comment by serby** [comment]
Now fixed in 6fa79a6b5c5d6c2c741e6bdd4a52f0cb60866f8d
