### ISSUE TITLE
Supporting other databases

### ISSUE THREAD

**Issue by jacques** [serby/ctrl#81]
Would it be possible to support databases like MySQL or Postgresql?

**Comment by serby** [comment]
Yes, we are hoping to have it much less tided to any specific database implementation, but have some work to do to abstract the data-layer for the standard bundles.

As it stands you can any add as many different types of database connections to the service locator and create bundles that use those databases. The core of control doesn't use mongo, it is only express sessions and the bundles that are currently using mongo, and express can easily be switched to used something else for sessions.

**Comment by domdoescode** [comment]
+1 for this.

We're currently using mongoose within certain bundles for entity schemas and model definition from an older project, however a unified abstraction layer would be amazing.

**Comment by ghost** [comment]
would be great if it could just use the file system for super easy deployment. I knwo this is not as fast as a database, but is enough for many possible use cases.

**Comment by serby** [comment]
@gedw99 In the 0.1 branch I've abstracted the data persistance layer so any storage type could be used. 

https://github.com/serby/ctrl/tree/0.1

There is already a in memory store, but if you wanted a disk based storage you only need to right an engine for 

https://github.com/serby/save

as per 

https://github.com/serby/save-mongodb

using 

https://github.com/serby/save/blob/master/lib/memory-engine.js

as a base but then saving as JSON to disk and loading back in on startup.

**Comment by serby** [comment]
Closing as this is now possible.
