### ISSUE TITLE
Forgotten password journey missing

### ISSUE THREAD

**Issue by panfantastic** [serby/ctrl#92]
Control needs a basic forgotten password journey for the admin.

**Comment by evlun** [comment]
@serby Can we assume that every machine running a Control instance has the capability to send e-mails? Perhaps this is something that should be defined in `properties.json`.

**Comment by serby** [comment]
SMTP host and port will be defined in the properties.js look at a Sun Perks from an example

**Comment by domdoescode** [comment]
Is control going to support different transport methods than SMTP in future?

**Comment by serby** [comment]
Like what, sendmail?

**Comment by domdoescode** [comment]
sendmail, Gmail, Amazon SES

**Comment by serby** [comment]
No I'm not going to have options for those in the properties.js If you need anything other than SMTP you can simply configure the mailer in the service locator in you own instances app.js
