### ISSUE TITLE
Asset delete does not work correctly

### ISSUE THREAD

**Issue by domdoescode** [serby/ctrl#93]
Currently appearing with a dialog box with [Object object] in, clicking either option closes the dialog without any change.

http://awesomescreenshot.com/045b8sy4d

**Comment by domdoescode** [comment]
Seems to be working fine after a few force refreshes and re-downloading control, sorry!

**Comment by bengourley** [comment]
Clear your cache and try again

Ben Gourley
[Sent from my phone]

**Comment by bengourley** [comment]
Ah you posted again before I responded! Glad it sorted itself out. I trust the stylesheet updated too and it looks different to your screenshot?

**Comment by domdoescode** [comment]
Looks much prettier now, yes =) I was a little miffed but thought it might be uncommitted code. Cheers for the help anyway!

**Comment by bengourley** [comment]
No probs. Luckily you had ImageMagick on your machine. Need to find somewhere to list that dependency.

**Comment by domdoescode** [comment]
I didn't actually, but I managed to google my way out of that one. Definitely worth stating as an issue, or a dependency for that bundle in the README

**Comment by bengourley** [comment]
Yeah, I think we're going to lift out pretty much all of the bundles from control core, leaving maybe admin and administrators so that it's completely decoupled. Then each bundle can have its own repo and so its readme will be more visible.

**Comment by domdoescode** [comment]
Ace =) I'm freed up a bit after this week, so I'm going to get back onto the control console. Working on legacy PHP stuff is making me feel a bit sick nowadays.
