### ISSUE TITLE
Remove all non-essential bundles from core

### ISSUE THREAD

**Issue by bengourley** [serby/ctrl#97]
I think we should remove all but the 'Admin' and 'Administrator' bundles. All other bundles that we maintain should be optional and live in their own repos.

Bundles should then be installed with https://github.com/serby/control-cli or until that is ready, `git clone bundle-repo`

Discuss?

**Comment by bengourley** [comment]
cc/ @serby @aduncan88 @domharrington @mjor @tomgco

**Comment by tomgco** [comment]
I agree, maybe have an example bundle included as well so that someone has a reference to a bundle that is not core to control?

**Comment by bengourley** [comment]
Well 'Administrator' is a good example of a simple bundle that makes us of generic. I think the documentation/tutorial should take care of showing any further examples.

**Comment by microadam** [comment]
Surely we need to keep Roles?

**Comment by evlun** [comment]
Definitely a sentiment I can get behind. That being said...

**administrator** relies on **generic** to create its views.

**generic** in turn uses **admin** to check if an user is allowed access to a particular view/action (this also means that **generic**, in its current state, only can be used for building admin interface components, which to me suggests that it really should be part of the **admin** bundle).

**admin** then requires the **rolesAdmin** bundle for its roleModel entity and functionality. **admin** also uses the **administrator** model (why haven't these bundles been combined?).

**rolesAdmin** then uses **generic** to generate its views, and **admin** for access control.

Right now, very few bundles are _actually_ decoupled - the core bundles pretty much all rely on each other.

**Comment by bengourley** [comment]
Yep, sorry missed that one. On the face of it, that coupled-ness suggests they should stay as they are rather essential to a 'CMS'.

It's ok to have dependencies between bundles. There is a distinction to be made between coupling and dependencies.

**Comment by evlun** [comment]
Inter-bundle dependencies aren't necessarily bad, but when you can't use any of those four bundles independently it might be an idea to combine them; especially as they're all vital for any kind of CMS functionality.

**Comment by microadam** [comment]
I think Erik makes a very good point.

I think we need to have a "basicAdmin" bundle (name TBC). Which wraps roles, rolesAdmin, admin, administrator and generic into a single bundle. If they all depend on each other and cannot work separately then I don't see the harm in it

**Comment by bengourley** [comment]
Sounds logical. Also, generic is something that has been shoehorned into a bundle, but it's more like an npm module. The only reason it is a bundle and not an npm module is that it contains views which should remain editable. Bears thinking about.

**Comment by serby** [comment]
Coupling and Dependency equate to the same thing.

Those four bundles have a complex circular dependency map as Erik has
shown. I worked hard to sperate them further but the required abstraction
was bloated. I'm happy with the current level of coupling between them.

Ideally there would be a control-core which has no bundles, properties.js,
server.js, app.js, expressApplication.js

Then control-basic (naming TBC) which would be what is currently
serby/control. This would be a minimal CMS with a homepage and wizards to
get everything setup. People would then install bundles and bundle-packs
via the control-cli. I still need everyones buy-in that control-cli is a
good idea. It was Dom Udall suggestion and I know additional package
managers are frowned upon by the node core team. Owen from socketstream did
explain why you need them if you have to install packages with views in
that need change in a recent NodeUp. Still I'd like to explore this further
with you guys.

On 25 July 2012 14:25, Ben Gourley <
reply@reply.github.com

> wrote:
> 
> Sounds logical. Generic is also something that has been shoehorned into a
> bundle, but it's more like an npm module. The only reason it is a bundle
> and not an npm module is that it contains views which should remain
> editable.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/serby/control/issues/97#issuecomment-7248802

## 

paul.serby@clock.co.uk
Chief Technology Officer

_Direct: +44 2030 516115__Mobile: +44 7881 550999_
*

## *
- http://www.clock.co.uk/
  *
  *
  *
  The Old School HouseBridge Road, Hunton Bridge,Kings Langley, WD4 8RQ
  Switchboard: +44 1923 261166www.clock.co.uk
  *
  *
- http://twitter.com/clock    https://github.com/clocklimited
  http://www.linkedin.com/company/clock-limited
  http://www.clock.co.uk/blog
  *
  *
  *
  _www.clock.co.uk/email-disclaimer_
  _clock.® is a Registered Trademark of Clock Limited in the European
  Community and other territories_

**Comment by domdoescode** [comment]
Definite +1 on all this.

**Comment by domdoescode** [comment]
Also related, probably discussed within Clock, bundle-specific style-sheets are also contained within the main project's public folder (asset manager for example).

**Comment by serby** [comment]
There is a post on this here: https://groups.google.com/forum/?fromgroups=#!topic/ctrl-cms/VY9Kd02xkYE

I'm going to close as an issue
