### ISSUE TITLE
Upload system duplicates pre-uploaded files

### ISSUE THREAD

**Issue by domdoescode** [serby/ctrl#98]
Using the asset manager with the same files produces duplicates in the data directory. More of a feature request, feel free to shoot me down if you don't feel it's necessary.

**Comment by bengourley** [comment]
What do you mean? You uploaded the same file twice?

**Comment by domdoescode** [comment]
Uploading the same file more than once appears in the asset list, which I feel is correct behaviour (for different titles or descriptions of the same thing, if you want it), however the actual file itself is uploaded twice as well, which could cause storage overhead if somebody uploads, say, a large video twice.

Here's a little screenr to explain a bit better - http://www.screenr.com/3FL8

**Comment by domdoescode** [comment]
Issue might be better placed in @domharrington's fileupload module, however I'm not 100% on the Control upload internals

**Comment by bengourley** [comment]
Cool. I get what you mean. This change would need to be in @domharrington 's fileupload middleware, as that's the thing that deals with the storage mechanism. Can't rely on the filename though, would need to inspect the bytes and compare with every existing file. Also what if (for some reason) you do actually want a duplicate file?

**Comment by domdoescode** [comment]
Fair point, couldn't think of a legit business model where you'd want a duplicate.. However some kind of option within the upload module could easily allow for that. I'll raise it with @domharrington, cheers =)

**Comment by serby** [comment]
We have employed a apprach in the past. We MD5 a file and if it already exists just point to that file. @domharrington should do this in his middleware if he isn't already. You have to be careful when you delete a file that there are no other items linked to it.

**Comment by domdoescode** [comment]
Is the asset management in the Control bundle style similar to that of Atrox, in terms of using a collection to store data about the binary file and it's location? If so I'm assuming the logic for whether a file is to be removed or not lies within the bundle, rather than the middleware?

**Comment by domharrington** [comment]
Just fixed all my tests for node 0.8 and express 3.0 and I pulled @domudall's change in with that.
